export let players = [
  {
    id:1,
    name: "M S Dhoni",
    playingRole: "Batsman",
    credit: 11,
  },
  {
    id:2,
    name: "Virat Kohli",
    playingRole: "Batsman",
    credit: 10,
  },
  {
    id:3,
    name: "Jasprit Bumrah",
    playingRole: "Bowler",
    credit: 12,
  },
  {
    id:4,
    name: "Rohit Sharma",
    playingRole: "Batsman",
    credit: 11,
  },
  {
    id:5,
    name: "Yuzvendra Chahal",
    playingRole: "Bowler",
    credit: 9,
  },
  {
    id:6,
    name: "Mohammed Shami",
    playingRole: "Bowler",
    credit: 8,
  },
  {
    id:7,
    name: "Suryakumar Yadav",
    playingRole: "Batsman",
    credit: 9,
  },
  {
    id:8,
    name: "Prasidh Krishna",
    playingRole: "Bowler",
    credit: 7,
  },
  {
    id:9,
    name: "Hardik Pandya",
    playingRole: "Batsman",
    credit: 9,
  },
  {
    id:10,
    name: "Shikhar Dhawan",
    playingRole: "Batsman",
    credit: 8,
  },
  {
    id:11,
    name: "Ravindra Jadeja",
    playingRole: "Batsman",
    credit: 10,
  },
  {
    id:12,
    name: "Arshdeep Singh",
    playingRole: "Bowler",
    credit: 6,
  },
  {
    id:13,
    name: "Ravichandran Ashwin",
    playingRole: "Bowler",
    credit: 11,
  },
  {
    id:14,
    name: "Deepak Chahar",
    playingRole: "Bowler",
    credit: 9,
  },
  {
    id:15,
    name: "Ruturaj Gaikwad",
    playingRole: "Batsman",
    credit: 8,
  },
  {
    id:16,
    name: "Deepak Hooda",
    playingRole: "Batsman",
    credit: 9,
  },
  {
    id:17,
    name: "Ishan Kishan",
    playingRole: "Bowler",
    credit: 10,
  },
  {
    id:18,
    name: "Shreyas Iyer",
    playingRole: "Batsman",
    credit: 10,
  },
  {
    id:19,
    name: "Venkatesh Iyer",
    playingRole: "Wicketkeeper",
    credit: 9,
  },
  {
    id:20,
    name: "Dinesh Karthik",
    playingRole: "Wicketkeeper",
    credit: 11,
  },
  {
    id:21,
    name: "Kuldeep Yadav",
    playingRole: "Bowler",
    credit: 9,
  },
  {
    id:22,
    name: "Bhuvneshwar Kumar",
    playingRole: "Bowler",
    credit: 12,
  },
  {
    id:23,
    name: "Mohammed Siraj",
    playingRole: "Bowler",
    credit: 10,
  },
  {
    id:24,
    name: "Devdutt Padikkal",
    playingRole: "Batsman",
    credit: 9,
  },
  {
    id:25,
    name: "Rishabh Pant",
    playingRole: "Wicketkeeper",
    credit: 10,
  },
  {
    id:26,
    name: "Moeen Ali",
    playingRole: "Bowler",
    credit: 9,
  },
  {
    id:27,
    name: "James Anderson",
    playingRole: "Bowler",
    credit: 12,
  },
  {
    id:28,
    name: "Jonny Bairstow",
    playingRole: "Batsman",
    credit: 11,
  },
  {
    id:29,
    name: "Sam Billings",
    playingRole: "Batsman",
    credit: 10,
  },
  {
    id:30,
    name: "Stuart Broad",
    playingRole: "Bowler",
    credit: 9,
  },
  {
    id:31,
    name: "Rory Burns",
    playingRole: "Bowler",
    credit: 8,
  },
  {
    id:32,
    name: "Jos Buttler",
    playingRole: "Batsman",
    credit: 10,
  },
  {
    id:33,
    name: "Zak Crawley",
    playingRole: "Batsman",
    credit: 9,
  },
  {
    id:34,
    name: "Sam Curran",
    playingRole: "Bowler",
    credit: 8,
  },
  {
    id:35,
    name: "Tom Curran",
    playingRole: "Bowler",
    credit: 7,
  },
  {
    id:36,
    name: "Chris Jordan",
    playingRole: "Bowler",
    credit: 11,
  },
  {
    id:37,
    name: "Jack Leach",
    playingRole: "Batsman",
    credit: 10,
  },
  {
    id:38,
    name: "Liam Livingstone",
    playingRole: "Batsman",
    credit: 12,
  },
  {
    id:39,
    name: "Reece Topley",
    playingRole: "Bowler",
    credit: 11,
  },
  {
    id:40,
    name: "David Willey",
    playingRole: "Wicketkeeper",
    credit: 9,
  },
  {
    id:41,
    name: "Joe Root",
    playingRole: "Batsman",
    credit: 9,
  },
  {
    id:42,
    name: "Ben Stokes",
    playingRole: "Batsman",
    credit: 10,
  },
  {
    id:43,
    name: "Pat Cummins",
    playingRole: "Bowler",
    credit: 11,
  },
  {
    id:44,
    name: "Aaron Finch",
    playingRole: "Batsman",
    credit: 10,
  },
  {
    id:45,
    name: "Cameron Green",
    playingRole: "Batsman",
    credit: 9,
  },
  {
    id:46,
    name: "Josh Hazlewood",
    playingRole: "Bowler",
    credit: 9,
  },
  {
    id:47,
    name: "Travis Head",
    playingRole: "Wicketkeeper",
    credit: 8,
  },
  {
    id:48,
    name: "Usman Khawaja",
    playingRole: "Batsman",
    credit: 11,
  },
  {
    id:49,
    name: "Marnus Labuschagne",
    playingRole: "Bowler",
    credit: 10,
  },
  {
    id:50,
    name: "Nathan Lyon",
    playingRole: "Bowler",
    credit: 9,
  },
];